### ISSUE TITLE
Pickling creates new Commit instances (huge memory usage with multiprocessing)

### ISSUE THREAD

**Issue by stspbu** [ishepard/pydriller#102]
**Describe the bug**
I started to parallelize my code, which used pydriller to extract the source code of methods from commits. For that purpose, I used **multiprocessing** package. I encountered very high memory usage in just a few hours. It's known that multiprocessing uses **pickle**. And, as I found out, pickling **Commit** objects leads to new Commit instances in memory. 

**To Reproduce**
I wrote a simple script to demonstrate the problem:
```
import pickle
import os

import objgraph
from pydriller import RepositoryMining

import settings


def main():
    repo_path = os.path.join(settings.get('git_repositories_dir'), 'trfl')
    repo = RepositoryMining(repo_path)

    commits = list(repo.traverse_commits())[:10]

    print(f'Starting with {len(objgraph.by_type("Commit"))}')
    for n, commit in enumerate(commits):
        pickle.dumps(commit)
        print(f'#{n+1} {len(objgraph.by_type("Commit"))}')
    # del commits
    print(f'Ending with {len(objgraph.by_type("Commit"))}')


if __name__ == '__main__':
    main()
```

The output is:
```
Starting with 29
#1 29
#2 29
#3 30
#4 32
#5 35
#6 39
#7 44
#8 50
#9 57
#10 65
Ending with 65
```

gc.collect() didn't helped, because new Commit objects referenced by old ones. You can see this by uncommenting `del commits`. The result should be `Ending with 0`.

**OS Version:**
- MacOS Mojave 10.14.6;
- Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
- PyDriller==1.11

----

- LSB Version:  1.4
   Distributor ID:  Arch
   Description:  Arch Linux
   Release:  rolling
   Codename:  n/a
   Linux ggnb-arch 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux;
- Python 3.8.2
- PyDriller==1.12

P.S. I've added info about multiprocessing in the title for people, who are facing the same problem in a similar way.

**Comment by ishepard** [comment]
Hi @stspbu,
thank you for catching this.

TBH, I never used (or tested) pydriller with multiprocessing. Overall, I think that if you need to parallelise the mining of, let's say, 1000 projects, you probably should run different instances of pydriller on different projects. Also, I had bad experiences on parallelising `Git` itself.

Said this, I will have a look on your code and see whether I can do something 😄 

I will also check why it uses all that memory, since it that shouldn't happen.

**Comment by marco-c** [comment]
I suggest using multithreading. It usually doesn't help to improve CPU-bound workloads with Python because of the GIL, but this workload is probably IO-bound (and moreover Pydriller's main job happens when running `git`, and while a thread runs `git` it yields for another thread to run, so basically the GIL almost doesn't hurt here).

I personally use it in a multithreaded fashion, where each thread has its own instance of `GitRepository`.

**Comment by stspbu** [comment]
Thanks you for the fast feedback.

When I wrote the first parallel version of my code (which eventually leaded me to this problem), I simply didn't think about the high cost of commits' exctraction at all. My code does pretty big calculations with them later, so I wanted to parallelize the most expensive part and look at results.

**Comment by ishepard** [comment]
@marco-c at this point I was thinking, do you think it would make sense to have a built-in option to parallelise RepositoryMining? So that we can better control it in case of bugs, etc. 
This is not the first time that someone complains about problems when using multiprocessing or multithreading...maybe it's time we do it

**Comment by marco-c** [comment]
@ishepard it might make sense, but I don't know exactly what API we could offer. At the very least, we should have some tests that make sure we can use some of the already existing APIs from multiple threads / processes.

**Comment by ishepard** [comment]
I am closing this issue as the problem didn't receive much attention.
