### ISSUE TITLE
Question: when do I should expect modified_file.old_path to be None?

### ISSUE THREAD

**Issue by stefanodallapalma** [ishepard/pydriller#105]
I have a question: the documentation for the object modifications states [*"**old_path**: the old path of the file (can be _None_ if the file is added)"*](https://pydriller.readthedocs.io/en/latest/modifications.html).

Does it mean the standard behaviour of git is to set up the old_path to *something != None* and in some cases to *None*? Or is this handled by PyDriller itself?

For example, with the following code:

```
for commit in RepositoryMining('https://github.com/snowplow/ansible-playbooks', to_commit='45376c4f43238a6c2ac10c64bcd6d3120d17ab08', reversed_order=True).traverse_commits():
    for modified_file in commit.modifications:
        if 'roles/neo4j-demo/tasks/main.yml' in (modified_file.old_path, modified_file.new_path):
            if modified_file.change_type == ModificationType.ADD:
                print(commit.hash, modified_file.old_path, modified_file.change_type)

```

I would expect:

the **modified_file.old_path** of *roles/neo4j-demo/tasks/main.yml* to be **None** (as it is added at commit [```70fc0074c32ec55053b47e285be0030e6022941e```](https://github.com/snowplow/ansible-playbooks/commit/70fc0074c32ec55053b47e285be0030e6022941e));

while the actual value is: *roles/neo4j-demo/tasks/main.yml*.

I am asking because when I used PyDriller in my code I assumed the old_path to be None when the file was added, and then I realized this.
However, adding the check ```if modified_file.change_type == ModificationType.ADD``` solved the problem :)

**Comment by ishepard** [comment]
Hi @stefanodallapalma!
The old path and new path are handled by git itself. 
In your case, I think you found a particular file addition since the file is empty. 
By running `git show`, the output is:
```
diff --git a/roles/neo4j-demo/tasks/main.yml b/roles/neo4j-demo/tasks/main.yml
new file mode 100644
index 0000000..e69de29
```
In this case Git doesn't even show the old path or new path. 

On the other hand, if we look at my repo, and let's take commit `e0c18a21fb918f40fdb74c81c6eacbf1abb62e16`, you can see that you added a file `docs/processmetrics.rst`, and `git show` output is:

```
diff --git a/docs/processmetrics.rst b/docs/processmetrics.rst
new file mode 100644
index 0000000..0a2000c
--- /dev/null
+++ b/docs/processmetrics.rst
@@ -0,0 +1,97 @@
....
```
In this case, you can see that the old path (starts with `---`) is null, and the new path is correct.

**Comment by stefanodallapalma** [comment]
Hi @ishepard, 
thanks for clarifying :)
