### ISSUE TITLE
The modified files in a commit do not appear

### ISSUE THREAD

**Issue by jacksonpradolima** [ishepard/pydriller#120]
**Describe the bug**
Hello,
I am trying to mine some repositories. However, I have some problems. The modified files in a commit do not appear. For instance, the commit [290b7370c57b00b99c69a653a33a646f1f169a23](https://github.com/alibaba/druid/commit/290b7370c57b00b99c69a653a33a646f1f169a23) from repository **alibaba/druid**.

Am I doing something wrong?

Thanks in advance for your help

**To Reproduce**
```python
from pydriller import RepositoryMining

url_repository = "https://github.com/alibaba/druid.git"
commits = ['290b7370c57b00b99c69a653a33a646f1f169a23']

repository_mining = RepositoryMining(
    url_repository, only_commits=commits).traverse_commits()

for commit in repository_mining:
    print(f"Hash {commit.hash} authored by {commit.author.name} includes {len(commit.modifications)} modified files: ")

    for modification in commit.modifications:
        print('Filename:', modification.filename)
        print('Size:', modification.nloc)
        print('Change Type:', modification.change_type)
        print('Cyclomatic Complexity:', modification.complexity)
```

**OS Version:**
 Windows

**Comment by jacksonpradolima** [comment]
PyDriller version: 1.15

**Comment by ishepard** [comment]
Hi @jacksonpradolima!
The reason why you don't see modifications in that commit is because it's a merge commit, and in those commits there are no changes (except for merge conflicts.)
For reference, see [link](https://github.com/ishepard/pydriller/issues/89#issuecomment-590243707).
But thank you for pointing it out, you reminded me that I didn't put it in the documentation

**Comment by jacksonpradolima** [comment]
Thank you
