### ISSUE TITLE
There is a difference in commit information between RepositoryMining and GitRepository

### ISSUE THREAD

**Issue by jacksonpradolima** [ishepard/pydriller#123]
Hello

I tested the GitRepository using the same example provided in issue #120, and the output is as follow:

```
Testing RepositoryMining:
290b7370c57b00b99c69a653a33a646f1f169a23 with 0 modified files.
Testing GitRepository:
290b7370c57b00b99c69a653a33a646f1f169a23 with 0 modified files.
``` 

However, using a different example with the commit [c1729c81d805913ef3d7737211f970db88c814f5](https://github.com/alibaba/druid/commit/c1729c81d805913ef3d7737211f970db88c814f5) from **alibaba/fastjson** repository, I had the following output:

```
Testing RepositoryMining:
Testing GitRepository:
c1729c81d805913ef3d7737211f970db88c814f5 with 7 modified files.
```

As you can observe, RepositoryMining is not retrieving the commit information. Using the command *git show* the information is presented.

The code used is below. For this example, I cloned the repository, and I am using the latest version of the PyDriller (1.15.1).

```python
from pydriller import RepositoryMining, GitRepository

#url_repository = "https://github.com/alibaba/fastjson.git"
url_repository = "fastjson"

commits = ['c1729c81d805913ef3d7737211f970db88c814f5']

repository_mining = RepositoryMining(
    url_repository, only_commits=commits).traverse_commits()


print("Testing RepositoryMining: ")
for commit in repository_mining:
    print(f"{commit.hash} with {len(commit.modifications)} modified files.")


print("Testing GitRepository: ")
gr = GitRepository(url_repository)
commit = gr.get_commit(commits[0])
print(f"{commit.hash} with {len(commit.modifications)} modified files.")
```

Thanks in advance for your help

**Comment by ishepard** [comment]
Hi @jacksonpradolima!
Thank you for opening the issue.
So I dug a bit deeper on the problem, and I discovered where the issue is: commit `c1729c81d805913ef3d7737211f970db88c814f5` is not in master branch.

One easy way to do it, is to run `git log | grep c1729c81d805913ef3d7737211f970db88c814f5`, you will see an empty list. This means that the commit is not reachable from the HEAD.
You can also see, by running `git branch --contains c1729c81d805913ef3d7737211f970db88c814f5`, which branches contain the aforementioned commit, and you'll also see an empty list.

Finally, to get the "real" branch where the commit is, you can run `git branch -r --contains c1729c81d805913ef3d7737211f970db88c814f5` (so it fetches also the remotes), and you will see the branch. However, unless you checkout that branch, you can't reach that commit.

Hope I clarified the issue! 
Cheers

**Comment by ishepard** [comment]
I probably forgot to mention the most important thing:
if you want to traverse that commit (all the commits reachable from all the refs), you need to use `git log --all`. In pydriller you can achieve this by using `include_refs`.

```
repository_mining = RepositoryMining(
    url_repository, only_commits=commits, include_refs=True).traverse_commits()


print("Testing RepositoryMining: ")
for commit in repository_mining:
    print(f"{commit.hash} with {len(commit.modifications)} modified files.")
```
prints:
```
Testing RepositoryMining: 
c1729c81d805913ef3d7737211f970db88c814f5 with 7 modified files.
```

**Comment by jacksonpradolima** [comment]
Perfect!
That's what I'm looking for!

Thanks
