### ISSUE TITLE
Analyze commits included in not merged PRs

### ISSUE THREAD

**Issue by danielnsilva** [ishepard/pydriller#142]
I am trying to use pydriller to analyze PRs commits. However, commits included in non-merged PRs can't be found in the local repo but still exists on GitHub. I wonder whether would be possible to recreate these commits in the local clone based on GitHub data, but I haven't made any progress. Any hint on how to analyze these commits?

**Comment by ishepard** [comment]
Hi @danielnsilva!
So, commits that are not merged can not be reached from the HEAD. That is, if we run `git log` from the HEAD, hence traverse back the history starting from the latest commit, we will not be able to reach those commits since they are not in the current branch.
However, if we change current branch, than we will be able to do it.
Meaning:
```
A -> B -> E -> F
      \ 
       C -> D
```
if we run `git log` here, we will get `A B E F`. because from `F` we not reach `C` or `D`.
However, if we first checkout `D` (or the branch), and then run `git log`, we will get `A B C D`. We will not get `E` or `F` though.

Alternatively, we can run `git log --all` from F, and we should get all the commits, even the ones that are not reachable from the current commit. Be aware that in this case git will try to order them based on the timestamp, but things might get messy: we might get `A B C D E F` or ` A B C E D F` or ` A B E F C D`..you will never be 100% sure :) 
To call pydriller with `--all`, you have to set `include_refs=True` in RepositoryMining. See https://pydriller.readthedocs.io/en/latest/repositorymining.html#other-configurations.

Hope it clarifies!

**Comment by danielnsilva** [comment]
Yes, it clarifies! Thank you @ishepard. I will try `include_refs=True` in RepositoryMining with some selected commits and see what happens.

**Comment by ishepard** [comment]
Awesome! Glad I helped! 
I will then close this issue.
Feel free to open a new one if you will have other questions!
