### ISSUE TITLE
How do we know if a commit is cherry picked?

### ISSUE THREAD

**Issue by raamojirao** [ishepard/pydriller#174]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I often have the problem of [...]

**Describe the solution you'd like**

**Additional context**
Add any other information or screenshots about the feature request here.

**Comment by ishepard** [comment]
Hi @raamojirao!
I had a look at https://stackoverflow.com/questions/2922652/git-is-there-a-way-to-figure-out-where-a-commit-was-cherry-picked-from.
It seems that you need to use a different command, `git cherry`, to get these commits.
Otherwise, if the `-x` option was used when cherry-picking, then it's recorded in the commit message. In this case you can check when traversing the commits.
For the other case, the command `git cherry` is not supported in Pydriller.
Hope it helps!
