### ISSUE TITLE
Implement traverse_releases()

### ISSUE THREAD

**Issue by matheusflauzino** [ishepard/pydriller#19]
My suggestion would to implement a function traverse_release(), so we can traverse releases commits, or the last release commit. 
We are working on paper in Brazil que analisa updates to each realease and this particular suggestion would help us greatly. Thanks!

**Comment by ishepard** [comment]
Hi @matheusflauzino! I like the idea of this filter. I was thinking, instead of creating a new function `traverse_release()`, I would prefer to put it as parameter of RepositoryMining, for example `only_releases=True`. Something like:

```
RepositoryMining("repo", only_releases=True).traverse_commits():
```
The change should be pretty trivial, you only have to obtain the list of commits that represent a release.

Can you do a PR with this feature?

**Comment by matheusflauzino** [comment]
> Hi @matheusflauzino! I like the idea of this filter. I was thinking, instead of creating a new function `traverse_release()`, I would prefer to put it as parameter of RepositoryMining, for example `only_releases=True`. Something like:
> 
> ```
> RepositoryMining("repo", only_releases=True).traverse_commits():
> ```
> The change should be pretty trivial, you only have to obtain the list of commits that represent a release.
> 
> Can you do a PR with this feature?

@ishepard Is a very good idea implement the filter `only_releases=True`, I don't know if I can accurately implemented this feature, since I'm new on Python, but can try. 

thanks in advance

**Comment by ishepard** [comment]
No worries for that, I can help! If you have questions, just write me an email or comment this issue! 

Thanks!
