### ISSUE TITLE
get the total number of contributors of the repository

### ISSUE THREAD

**Issue by mohmehmo** [ishepard/pydriller#198]
Firstly, thanks a lot for your great framework. 
One of the requirements for analyzing repositories is the number of contributors, I mean the number of persons who collaborate on the repository. But I can not find any command in PyDriller documentation to get total number of contributors. 
Is there any possibility to add this feature in the near future?

Thanks.

**Comment by avandeursen** [comment]
The `author` field of a `Commit` gives the author of that commit. So you can simply traverse over all commits in a `Repository`, and collect the authors in a set.

Some authors may use different email addresses and/or names, so you probably need to do a bit of analysis on the author set to merge likely equivalent authors.

**Comment by mohmehmo** [comment]
@avandeursen thanks for your comment. I was also thinking about your suggestion. But the problem is because of the significant number of repositories that I am analyzing. I am studying more than 100,00 repositories, and if I want to use this approach, it will take a long time to do this for all repositories one by one. I am looking for something like "total_commits()" method that returns the total number of collaborators.

**Comment by ishepard** [comment]
Hi @mohmehmo! Thanks for reaching out.
Arie's suggestion is the correct solution to your problem. There won't be a command that automatically get the list of authors in Pydriller, mainly because it's just 1 line of code 😄 

>  I am studying more than 100,00 repositories, and if I want to use this approach, it will take a long time to do this for all repositories one by one

Mmmm no I don't think so. Pydriller can analyze multiple repos at the time. So just pass: 
```
list_repositories = ["https://github.com/author/repo", "https://github.com/author/repo1", "https://github.com/author/repo", ...]

for commit in Repository(list_repositories).traverse_commits():
    ....
```

This will cycle over all the repo.

Now, how to get the list of authors I will leave it to you. But as Arie suggested, `commit.author` contains both name and email of the author of the commit. Start from there. 

Also, if you take this approach of analyzing multiple repos, you could have a dictionary where the keys are repo names and values are the authors set. In which case you will find useful to have `commit.project_name` (or `project_path`, if you have multiple repos with the same name).

**Comment by ishepard** [comment]
Looks like it is solved. Closing the issue then.

Feel free to re-open it if you have more questions, or just ping me 😃
