### ISSUE TITLE
Popup keeps asking me for my github username preventing code from running autonomously.

### ISSUE THREAD

**Issue by rogerjbos** [ishepard/pydriller#250]
When I put my code in a look with a list of repos,  a pop up periodically appears asking for my Github username.  When I type it in the loop continues, but the popup makes it unreliable to use for many repos.

I am not sure if this is a bug or maybe a feature request, but from reading the docs I don't see a Github token mentioned anywhere.  If the user could supply a Github access token that might solve the issue.  I tried adding my credentials and token with `gh auth login`, but that doesn't help (the popup still occurs).

I am running on a Mac and Linux VM and I get the same result on both.  Apologies if this is addressed somewhere and I just missed it.

**Comment by stefanodallapalma** [comment]
Hi @rogerjbos,

Are those repos private? The reason why you can't supply a GitHub access token is because PyDriller is a Git framework (not GitHub). I suggest you clone the private repositories first -- think of a script making curl calls with your authentication token -- and pass the path to the local repository instead of the remote one. Does it make sense?

Hope that helps!

**Comment by rogerjbos** [comment]
Ok.  I understand now.  I was just misunderstanding how it was meant to be used.  Thanks for getting back to me.
