### ISSUE TITLE
Is there a way to traverse commits on a single file?

### ISSUE THREAD

**Issue by kanghj** [ishepard/pydriller#30]
It will be nice if I was able to traverse through the commits through a single file's history. The file could be specified as a parameter to RepositoryMining, perhaps? I can try adding a feature like this when I have more time, if @ishepard is interested.

**Comment by ishepard** [comment]
Hi @kanghj,
it could indeed be a nice feature. I already started working on a function called `traverse_file` (to be used instead of `traverse_commits`) in a branch called `traverse_file`. However, it could be nice to have a parameter in `RepositoryMining` to which you pass a file and it returns the list of commits. Something like:

```
for commit in RepositoryMining("repo", filepath="/path/to/file").traverse_commits():
    # do something
```

If you want to implement it, go ahead. As an example, you can see [this](https://github.com/ishepard/pydriller/blob/4c001de64f43838edb05c8b98fd0e804d82e8dea/pydriller/git_repository.py#L267) function I created that given a file returns the list of commits. You have of course to create a new parameter, and add tests :)
