### ISSUE TITLE
Commit filter only_authors raising "unexpected keyword argument" error

### ISSUE THREAD

**Issue by ntabassum7** [ishepard/pydriller#34]
The only_authors() commit filter is not working and raising an error. 
I'm trying to run the example given in the [configuration page](https://pydriller.readthedocs.io/en/latest/configuration.html)

Following is the error that I'm getting:
```
for commit in RepositoryMining('repos/caboche', only_authors=['jmettraux']).traverse_commits():
TypeError: __init__() got an unexpected keyword argument 'only_authors'

```
I'm using Windows powershell, python 3.6.5.

**Comment by ishepard** [comment]
Hi @ntabassum7 ! Thank you for opening an issue.
Unfortunately, I can't replicate the error (I tried on my laptop, Travis CI and Appveyor and it works on all of them). My concern is that, since *only_authors* is a relatively new feature, you don't have an updated version of PyDriller. Can you double check that PyDriller is version 1.7?

**Comment by ishepard** [comment]
this error `TypeError: __init__() got an unexpected keyword argument 'only_authors'` means that **only_authors** is not in the **init** function of RepositoryMining, however, you can see that it is: https://github.com/ishepard/pydriller/blob/fbba3a46814b058b5601fc0eade3e358f5ef77bd/pydriller/repository_mining.py#L40.

**Comment by ntabassum7** [comment]
Thanks! I was in fact using a older version (1.2.3) of pydriller, i updated it and it works absolutely fine!

**Comment by ishepard** [comment]
Perfect 👍
