### ISSUE TITLE
Lost diffs

### ISSUE THREAD

**Issue by sims1253** [ishepard/pydriller#42]
**Describe the bug**
When iterating through the commits of a repo and analyzing the diffs for each commit sometimes the diffs are missing.
I also hat this happen when running it over the Linux kernel and apache httpd but I don't have examples at hand.

**To Reproduce**
I am testing this on https://github.com/GNOME/evolution
commit sha is 756c8abcb840b8da588031f4a0d7e1fc979fab70
https://github.com/GNOME/evolution/commit/756c8abcb840b8da588031f4a0d7e1fc979fab70

Using git directly:
`git diff 756c8abcb840b8da588031f4a0d7e1fc979fab70^!`

Gives the same as using git-python directly:
```
repo = Repo("./")
commit = repo.commit("756c8abcb840b8da588031f4a0d7e1fc979fab70")
diff = commit.diff(commit.parents[0], create_patch=True)
```
But when using pydriller like this:
```
commits = reversed(list(RepositoryMining("./").traverse_commits()))
for commit in commits:
    if commit.hash == "756c8abcb840b8da588031f4a0d7e1fc979fab70":
        for mod in commit.modifications:
            if mod.filename == "gnome-canvas-text.c":
                print(mod.diff)
                return

```

It gives an empty diff.

**OS Version:**
Using Antergos Linux (Arch based), python 3.7, GitPython 2.1.11 and pydriller 1.7

**Comment by ishepard** [comment]
Hi @sims1253 ! Thank you for opening the issue. 
After a quick investigation, I discovered that the problem is the decoding in UTF-8. The file you've pointed out has 2 "strange" characters: 
**Line 35: Port to Pango co-done by Gerg\xf5 \xc9rdi.** 
PyDriller fails to decoding it. 

AFAIK, I don't see a problem on this. What do you think?

**Comment by sims1253** [comment]
Makes sense I think. Damn though :see_no_evil: 
It might be nice to log a message about this so it is more explicit I think.

Do you have an idea how to work around this?

**Comment by ishepard** [comment]
Yeah, you're right. I log it in this [line](https://github.com/ishepard/pydriller/blob/3e757de698fd59c693fab5d24e0fbae5ef79824d/pydriller/domain/commit.py#L421), but it's probably lost in between all the other logs. 

The reason why I use decode UTF-8 is because it automatically translates "\n" in escapes, "\t" in tabs, etc. 
A possibility might be to keep this behavior in normal cases, while returning the encode diff when the decoding doesn't work. However, I feel that this might lead to inconsistency. I will try it in the next days to see if it could work 👍

**Comment by sims1253** [comment]
Found the log message. It was indeed just swamped and I didn't look hard enough.

UTF-8 seems to be a sensible default I think. The whole decoding problem probably can't really be solved.
The options that come to my mind would be:
  - Throw error if UTF-8 doesn't work. This would break pydrill on many projects so probably not desired.
  - Add an option to raise an exception on an encoding error. This would allow the user to decide how to handle it. It could maybe be combined with the following.
  - Return the encoded diff when decoding doesn't work (like you proposed). 

I like the idea of adding an option, as it gives the user explicit control of the behavior.

**Comment by ishepard** [comment]
So, after a bit of decoding documentation, I discovered there is a flag "ignore" to ignore non-decodable characters. Now it works 😄 BTW, it's more efficient if you re-write your code like this:

```
from pydriller import RepositoryMining

for commit in RepositoryMining("/tmp/evolution",
                               single="756c8abcb840b8da588031f4a0d7e1fc979fab70",
                               reversed_order=True).traverse_commits():
    for mod in commit.modifications:
        if mod.filename == "gnome-canvas-text.c":
            print(mod)
```

I am gonna release a patch soon. Thanks!

**Comment by sims1253** [comment]
Nice!
And thanks for the hint :)

**Comment by sims1253** [comment]
I'm closing this as you pushed the commit.

**Comment by ishepard** [comment]
Just wanted to tell you that I just release PyDriller 1.8 with the fix 👍 thanks again!

**Comment by sims1253** [comment]
nice thanks :)
