### ISSUE TITLE
"Now the user needs to change from_commit and to_commit if reversed_order is True" may be misleading

### ISSUE THREAD

**Issue by stefanodallapalma** [ishepard/pydriller#83]
Hi @ishepard ,

I have noticed that during commit https://github.com/ishepard/pydriller/commit/bec86e2fe0c027032e8f66427eb4fd363c65e838 you have swap  ```from_commit``` and ```to_commit``` in the test data for the process metrics to reflect the changes you have done in commit https://github.com/ishepard/pydriller/commit/f84047a2579a4f0b282aebc66a3e6a8d13ae2871.

Although those tests pass, I think it could be misleading telling the user to reverse the order of the two parameters, for two reasons:

1. Different applications already use PyDriller, and I imagine that some of them use the ```reverse_order``` and need to change the code accordingly;

2. In the specific case of the implemented process metrics, the user does not know (and is not assumed to know) that we set up ```reverse_order = True``` in the body of the metrics. When a user calls ```commits_count('pydriller', from_commit='commit_1', to_commit='commit_10')```, he/she expects to analyse the commits in chronological order from ```commit_1``` to ```commit_10```. 
The current version returns the wrong result, and the user has to call ```commits_count('pydriller', from_commit='commit_10', to_commit='commit_1')``` instead, which is IMHO a bit confusing.

Here the alternatives that I propose:

1. Handle the ```reverse_order``` in the constructor of ```RepositoryMining```, by swapping ```from_commit``` and ```to_commit``` in the configuration dict when ```reverse_order == True```, instead of letting the user do so;

2. We can leave everything as it is (but take care of point 1 in the previous list), and I can change the process metrics accordingly, by simply swapping the two variables when calling ```RepositoryMining``` in the body of each metrics.

Let me know what do you think.

**Comment by ishepard** [comment]
Hi @stefanodallapalma! Yes indeed, you're right. I changed the behaviour. 
I think it's just a matter of deciding who to upset. 

If I have 4 commits (A, B, C, D), and I ask them in reversed order, I will obtain (D, C, B, A). Now, given this list, what's the `from_commit` and `to_commit`?

Yesterday I was debugging a repo, and I was printing the commits in reverse order, and I was looking at something like:
```
...
01d2f2fbeb6980cc5568825d008017ca8ca767d6
6256be7051d144bf94b9cfb2c063dbc8de436c89
c8e703b2251ea7d887982723eb25a50ffb4311e8
542c32df3bddffc27b386c9107b6498ca190c416
177727e41f67f3663e8db8aa1d3555ce12f5d6d4
b35bce26e3fd1700de42b89fd3b1b9d1cecbe053
12bbfcc06b93bfa81400f75615472424ef8272bc
...
```

Now, let's say I would like to filter them out. Given what I printed, I would naturally do is:
```
for commit in RepositoryMining("repo", from_commit="01d2", to_commit="12bb")
```
But then it wouldn't work. So I had to invert them, which is confusing. That's why I decided to delete that piece of code, and let the user invert them. 

As for the process metrics, we can solve the problem by manually inverting them before running the study. 
Here I am just discussing, I am not the BDFL of pydriller, just a guy with some ideas 😄 maybe I am wrong!

**Comment by mauricioaniche** [comment]
Maybe there's no need for the `reverse_order` config. Pydriller could detect whether A happened before B, or B happened before A, and go for it. This `reverse_order` thing seems like more of a "Git low-level thingy", and maybe it should indeed be abstracted away.

**Comment by ishepard** [comment]
Mmmm, indeed, that would work in case of from_commit and to_commit. We can just check if they are in the right order, and if they are not, we swap them.

However, I am not in favour of removing the option, since sometimes we need to traverse the order from a different direction. TBH, what we call "reverse" it's actually the default behaviour of git. And what we call "default" it's actually reversed in git.

**Comment by stefanodallapalma** [comment]
> Hi @stefanodallapalma! Yes indeed, you're right. I changed the behaviour.
> I think it's just a matter of deciding who to upset.
> 
> If I have 4 commits (A, B, C, D), and I ask them in reversed order, I will obtain (D, C, B, A). Now, given this list, what's the `from_commit` and `to_commit`?
> 
> Yesterday I was debugging a repo, and I was printing the commits in reverse order, and I was looking at something like:
> 
> ```
> ...
> 01d2f2fbeb6980cc5568825d008017ca8ca767d6
> 6256be7051d144bf94b9cfb2c063dbc8de436c89
> c8e703b2251ea7d887982723eb25a50ffb4311e8
> 542c32df3bddffc27b386c9107b6498ca190c416
> 177727e41f67f3663e8db8aa1d3555ce12f5d6d4
> b35bce26e3fd1700de42b89fd3b1b9d1cecbe053
> 12bbfcc06b93bfa81400f75615472424ef8272bc
> ...
> ```
> 
> Now, let's say I would like to filter them out. Given what I printed, I would naturally do is:
> 
> ```
> for commit in RepositoryMining("repo", from_commit="01d2", to_commit="12bb")
> ```
> 
> But then it wouldn't work. So I had to invert them, which is confusing. That's why I decided to delete that piece of code, and let the user invert them.
> 

Ciao @ishepard,
with this example the new behavior is much more clear to me.  
I've struggled a bit understanding it by just reading at the [doc](https://github.com/ishepard/pydriller/blob/master/docs/configuration.rst).
If you decide to proceed that way, please consider adding a similar example in the doc.

> As for the process metrics, we can solve the problem by manually inverting them before running the study.

Indeed, but we have to account for it also in their implementation by inverting ```from_commit``` and ```to_commit```. I can create a pull request for them.
Today I was analyzing the commits in their correct order, let's say (A, B, C, D) and wanted to compute the commits count metric from A to D. 
With the new release I had to setup ```from_commit: D, to_commit:A``` to made it work, which is counter-intuitive.

**Comment by ishepard** [comment]
Yeah you're right, sorry for that. But @mauricioaniche's idea is better I think. Let's just add a check whether from_commit and to_commit are in the right order (we can copy paste my old code, and just add the check). I will add this fix soon.

**Comment by stefanodallapalma** [comment]
Yes, I agree, I like his solution :+1:
