### ISSUE TITLE
Support using topological order for traversing commits

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#94]
It can be useful in cases like https://github.com/mozilla/gecko-dev (see also #93).

**Comment by ishepard** [comment]
I think we could change this issue to
"Let's use git commands to filter the commits instead of doing it manually".

Meaning, to filter by date, instead of checking the commit dates manually, let's just run `git log --after=SOMEDATE`.

To filter by commits, instead of looking at the commit hashes, let's just run `git log FROMCOMMITHASH..TOCOMMITHASH`

This would resolve so many problems 😄 
Though it's gonna ask for some re-writing since we will need to pass commands to `git log`. I am not even sure if GitPython allows that.

**Comment by mauricioaniche** [comment]
Maybe it's time for pydriller to stop "flattening out" the list of commits (and thus, assume that history is linear), and give to the user a more sound representation of the history of the project, e.g., a simple graph. 

Just to give a concrete example of where it would be useful: in previous papers, when I tried to identify how long a code smell would survive, it was common to see "smell, not smell, smell not smell, ...", because the smell was removed in one branch and not in the other, so simply visiting commits in order they appear is not enough. Back then, I sorted it out by telling Git (and old-but-dead Repodriller) to only follow left nodes, in an attempt to flatten out the history.

Maybe a simple "number" in the commit that would represent the "path" it is in might be enough.  
Adding a number that represents the path number would enable me to either treat it or filter out paths I don't care. To understand more about this number I'm suggesting, try `gitk`. Each color would be a different number.

**Comment by ishepard** [comment]
I think pydriller should be as similar as possible to git. That's the main goal here: take advantage of python to do things that from the terminal would be more difficult.

Said this, we also know when pydriller is used: in MSR studies. So we should also take this into consideration, and ask ourselves what could make things easier for researchers doing MSR.

The way I see it, these kind of extensions should be separate. I like a lot what a couple of students and a Ph.D. in Leiden (@NullConvergence) are doing: they are trying to represent the repo as a graph using Pydriller. This has the enormous advantage that, after a first phase in which pydriller runs, the query on the graph are really fast. And they are visually pretty. This could be a very nice tool that researchers could use.

Using `gitk` could be again another tool, maybe an extension of pydriller.

**Comment by mauricioaniche** [comment]
> I think pydriller should be as similar as possible to git.

You mean _as possible to git log_, then.

Is this graph tool available somewhere?

**Comment by ishepard** [comment]
Yes we can say similar to `git log`.
We have to stick to what git returns to the terminal (by default). I understand that we can customise the output of `git log`, and we for sure can do it in Pydriller if we feel like it, but let's keep things simple by default. 

Let's just use `git log` and display the results that you should obtain by running the same command on the terminal (this is what Pydriller does now).

For the future, let's think about how we can customise the output of `git log` to help researchers in tasks like the one you reported above. Maybe we can even change to `gitk` just for that case.

> 
> Is this graph tool available somewhere?

Not that I know, but we should ask the guys. 
They were still adding features last time I talked to them.

**Comment by NullConvergence** [comment]
The tool is available here: https://github.com/NullConvergence/GraphRepo

It basically indexes a repository in Neo4j and allows any tips of queries. You can find the details in the documentation, it only requires Docker. 

A visualization is available by default in Neo4j so start with a small repo 😄

**Comment by NullConvergence** [comment]
I forgot to mention that we have complex visualization prototypes, but they are not as flexible as Neo4j, because they don't (yet) allow queries. If you are interested and want to get your hands 'dirty', let me know.

**Comment by marco-c** [comment]
I guess adding the `--topo-order` option should not be feasible, since #96.

**Comment by ishepard** [comment]
It's the opposite: since I now use git filters, everything that is in [this page](https://git-scm.com/docs/git-rev-list) can be added as a flag to pydriller.
We definitely can add `--topo-order`, `--author-date-order`, `--date-order`, or whatever flag you like from that list 😄

**Comment by marco-c** [comment]
There was a typo in my comment, `not` was supposed to be `now` :P
